# .github/workflows/deploy.yml
name: Build and Deploy Databricks Bundle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-bundle:
    name: Validate and Deploy Bundle to Dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Databricks CLI
        run: |
          pip install --upgrade pip
          # Install a version that includes `bundle`
          pip install --upgrade "databricks-cli>=0.18.0"

      - name: Verify Databricks CLI Installation
        run: |
          echo "--- Which databricks is being used? ---"
          which databricks
          echo "--- Databricks CLI version ---"
          databricks --version
          echo "--- Bundle commands available? ---"
          databricks bundle --help

      - name: Validate Databricks Bundle for Dev target
        run: databricks bundle validate
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

      - name: Deploy Databricks Bundle to Dev target
        run: databricks bundle deploy -t dev
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
