name: Build and Deploy Databricks Bundle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-bundle:
    name: Validate and Deploy Bundle to Dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install PEP 517 build tool
        run: |
          pip install --upgrade pip
          pip install build

      - name: Install Databricks CLI v2 (Public Preview with bundle)
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sudo sh

      - name: Verify Databricks CLI Installation
        run: |
          echo "Databricks CLI version:"
          databricks --version
          echo "Bundle commands available:"
          databricks bundle --help

      - name: Validate Databricks Bundle
        run: databricks bundle validate
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

      - name: Deploy Databricks Bundle to Dev
        run: databricks bundle deploy -t dev
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
